version: '3.8'
services:
  anaconda:
    image: continuumio/anaconda3
    volumes:
       - ../:/opt/notebooks
    ports:
      - "8888:8888"
    command:
      /bin/bash -c "/opt/conda/bin/conda install jupyter -y --quiet && /opt/conda/bin/jupyter notebook --notebook-dir=/opt/notebooks --ip='0.0.0.0' --port=8888 --no-browser --allow-root"
    tty: true
    networks:
      - python-docker
  
  
  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest
    ports:
      - 11430:11434
    networks:
      - python-docker
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  unstructured-api:
    image: downloads.unstructured.io/unstructured-io/unstructured-api:latest
    ports:
      - "8000:8000"
    networks:
      - python-docker
  
networks:
  python-docker:
    external: false
volumes:
  ollama: {}